sudo: required

services:
  - docker

script:
  - docker-compose build
  - docker-compose run --rm php composer install --prefer-dist --no-progress --no-suggest --no-interaction
  - docker-compose run --rm php bin/console security:check
