imports:
    - { resource: schema/enums.yml }
    - { resource: schema/shared_classes.yml }
    - { resource: schema/places.yml }
    - { resource: schema/activities.yml }


annotationGenerators:
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\PhpDocAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\DoctrineOrmAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\ConstraintAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\ApiPlatformCoreAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\SerializerGroupsAnnotationGenerator

useInterface: true

types:



    ### Abstract & Base Classes ###

    ImageObject:
        parent: false
        properties:
            caption: ~
            exif: { range: text }
            thumbnail: ~


    Person:
        abstract: true
        parent: false
        properties:
            name: ~
            address: { range: PostalAddress }
            familyName: ~
            givenName: ~
            gender: ~
            birthDate: ~
            telephone: ~
            email: ~
