types:
    ActivityLocation:
        guessFrom: Place
        parent: Place
        properties:
            containedInPlace: { range: ActivityRegion, cardinality: "(1..1)" }
            address: { range: PostalAddress }
            #aggregateRating: ~
            #amenityFeature: ~
            #event: ~
            logo: ~
            maximumAttendeeCapacity: ~
            openingHoursSpecification: ~
            specialOpeningHoursSpecification: ~
            #photo:
            #review: ~
